# modified version of sandeep's - https://github.com/sandeepmistry/arduino-nRF5/.travis.yml
language: generic
addons:
  apt:
    packages:
      - libc6:i386
      - libstdc++6:i386
env:
  global:
    - IDE_VERSION=1.8.4
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - arduino --pref "boardsmanager.additional.urls=https://sandeepmistry.github.io/arduino-nRF5/package_nRF5_boards_index.json,https://micooke.github.io/package_nRF5_smartwatches_index.json" > /dev/null
  - arduino --install-boards sandeepmistry:nRF5
  - arduino --install-boards micooke:nRF5
  - buildExampleSketch() { arduino --verbose-build --verify --board $1 $HOME/arduino-ide/examples/$2/$3/$3.ino; }
install:
#  - mkdir -p $HOME/Arduino/hardware/sandeepmistry
#  - ln -s $PWD $HOME/Arduino/hardware/sandeepmistry/nRF5
script:
  - buildExampleSketch micooke:nRF5:IDO003 01.Basics Blink
  - buildExampleSketch micooke:nRF5:ID100HR 01.Basics Blink
  - buildExampleSketch micooke:nRF5:ID107HR 01.Basics Blink
  - buildExampleSketch micooke:nRF5:ID107HRPlus 01.Basics Blink
